"""
Data models for the AI Risk Scorer pipeline.

This module defines the structured contracts for loan applications, 
intermediate extraction signals, and final risk assessments.
"""

from enum import Enum
from decimal import Decimal
from typing import Literal
from pydantic import BaseModel, Field, ConfigDict, field_validator


class RiskLevel(str, Enum):
    """Enumeration of possible risk categories."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ApplicationRequest(BaseModel):
    """
    The initial entry point for a loan application.

    Contains the raw unstructured text provided by the applicant 
    and a unique identifier for tracking.
    """

    model_config = ConfigDict(frozen=True)

    application_id: str = Field(..., min_length=1)
    text: str = Field(..., description="The raw free-text loan application")


class ExtractedSignals(BaseModel):
    """
    The sanitized data firewall between raw input and scoring logic.

    This model represents the output of the first LLM pass. It ensures 
    that only validated, structured data is passed to the final analysis stage.
    """

    model_config = ConfigDict(
        frozen=True, extra="forbid", json_encoders={Decimal: lambda v: float(v)}
    )

    monthly_income_usd: Decimal | None = Field(
        None, ge=0, description="The applicant's monthly income in USD"
    )
    stated_employment: str | None = Field(
        None, max_length=100, description="The reported job title or employment status"
    )
    loan_purpose: str | None = Field(
        None, max_length=200, description="The intended use of the funds"
    )
    mentions_debt: bool = Field(
        default=False, description="Whether the applicant acknowledged existing liabilities"
    )
    sentiment: Literal["positive", "neutral", "negative"] = Field(
        ..., description="The general tone of the application text"
    )

    @field_validator("monthly_income_usd", mode="before")
    @classmethod
    def handle_empty_income(cls, v):
        """Ensures empty strings or nulls from LLM are handled as None."""
        if v == "" or v is None:
            return None
        return v


class RiskScore(BaseModel):
    """
    The final output of the risk assessment pipeline.

    Includes the numerical risk probability, categorical risk level, 
    and the qualitative reasoning generated by the analysis engine.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    application_id: str
    score: int = Field(
        ..., ge=0, le=100, description="Risk probability score (100 = highest risk)"
    )
    risk_level: RiskLevel
    reasoning: str = Field(
        ..., min_length=20, description="Detailed justification for the assigned risk score"
    )


class PaymentRequest(BaseModel):
    """Request schema for initiating a processing fee payment."""

    application_id: str
    email: str = Field(..., pattern=r"^\S+@\S+\.\S+$")
    amount_usd: Decimal = Field(Decimal("5.00"), ge=0)


class PaymentIntent(BaseModel):
    """Response schema containing Stripe payment details."""

    application_id: str
    client_secret: str
    payment_intent_id: str
    status: str


class AssessmentResult(BaseModel):
    """Unified response containing payment status and optional risk assessment."""

    application_id: str
    payment_status: str
    risk_score: RiskScore | None = None
    message: str
